<?php

namespace Calor\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Calor\ApiBundle\Entity\User;


/**
 * MealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRepository extends EntityRepository
{
    public function getList($filter, $page, $perPage){
        $qb = $this->createQueryBuilder('m');
        if(isset($filter['user'])){
            $qb->where('m.user = :user')->setParameter('user', $filter['user']->getId());
        }


        if(isset($filter['date'])){
            $qb->andWhere('m.date >= :date0')->setParameter('date0', $filter['date'][0]);
            $qb->andWhere('m.date <= :date1')->setParameter('date1', $filter['date'][1]);
        }

        if(isset($filter['time'])){
            $qb->andWhere('m.time >= :time0')->setParameter('time0', $filter['time'][0]);
            $qb->andWhere('m.time <= :time1')->setParameter('time1', $filter['time'][1]);
        }

        if(isset($filter['name'])){
            $qb->andWhere('m.name LIKE :name')->setParameter('name', '%'.$filter['name'].'%');
        }
        $qb->addSelect('m.id');

        $totalQB = $qb->getQuery();

        $total = count($totalQB->getResult());

        $qb->setFirstResult(($page-1)*$perPage);
        $qb->setMaxResults($perPage);
        $list = $qb->getQuery()->getResult();

        return array('total'=>$total, 'page'=>$page, 'list'=>$list);
    }

    public function getReport($filter, $mode){


        $emConfig = $this->getEntityManager()->getConfiguration();
        $emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');
        $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');
        $emConfig->addCustomDatetimeFunction('DAY', 'DoctrineExtensions\Query\Mysql\Day');
        $emConfig->addCustomDatetimeFunction('DATE_FORMAT', 'DoctrineExtensions\Query\Mysql\DateFormat');


        $qb = $this->createQueryBuilder('m');
        $qb->select('SUM(m.calories) as total');



        if(isset($filter['user'])){
            $qb->where('m.user = :user')->setParameter('user', $filter['user']->getId());
        }

        if(isset($filter['date'])){
            $qb->andWhere('m.date >= :date0')->setParameter('date0', $filter['date'][0]);
            $qb->andWhere('m.date <= :date1')->setParameter('date1', $filter['date'][1]);
        }

        if(isset($filter['time'])){
            $qb->andWhere('m.time >= :time0')->setParameter('time0', $filter['time'][0]);
            $qb->andWhere('m.time <= :time1')->setParameter('time1', $filter['time'][1]);
        }

        if($mode == 'daily'){
            $qb->groupBy('m.date');
            $qb->addSelect("DATE_FORMAT(m.date, '%Y-%m-%d') as day");
            $qb->addSelect('YEAR(m.date) as year');
            $qb->addSelect('MONTH(m.date) as month');
        }

        if($mode == 'monthly'){
            $qb->addSelect('YEAR(m.date) as year');
            $qb->addSelect('MONTH(m.date) as month');
            $qb->groupBy('year')->addGroupBy('month');
        }

        if($mode == 'yearly'){
            $qb->addSelect('YEAR(m.date) as year');
            $qb->groupBy('year');
        }


        $report = $qb->getQuery()->getResult();
        return $report;


    }
}
