<?php

namespace Calor\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUserByToken($token){
        $query =

            $this->createQueryBuilder('u')
                ->select('u.id, u.username, u.target, u.displayName, s.expiresAt, s.token')
                ->leftJoin('u.sessions', 's')
                ->where('s.token = :token')
                ->setParameter('token', $token)
                ->getQuery()
            ;



        try {
            $user = $query->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            $user = null;
        }


        return $user;

    }
}